name: nim_chatkit_sticker
description: Optional Sticker extension for NetEase YunXin IM ChatKit UI.
version: 10.9.60
homepage: https://github.com/netease-kit/nim-uikit-flutter

environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  netease_corekit:
    ">=1.3.1 <1.4.0"
  nim_chatkit_ui:
#    ">=10.9.60 <10.9.70"
    path: ../nim_chatkit_ui
  yunxin_alog: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sticker/
    - assets/sticker/ajmd/
    - assets/sticker/lt/
    - assets/sticker/xxy/
